version: "3.9"
volumes:
  chat-db-store:

services:
  workspace:
    build: ./php
    volumes:
      - ../src:/work

  nginx:
    image: nginx:1.20-alpine
    ports:
      # - 10080:80
      - 80:80
    volumes:
      - ../src:/work
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  mysql:
    build: ./mysql
    volumes:
      - chat-db-store:/var/lib/mysql